name: Hyundai Bluelink Control
version: "1.1.1"
slug: hyundai-bluelink
description: Control your Hyundai/Kia vehicle via Bluelink/UVO
url: https://github.com/fhfournier/home-assistant-hyundai-palisade-command
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  username: ""
  password: ""
  pin: ""
  vehicle_id: ""
  region: "Canada"
  brand: "Hyundai"
  port: 8099
schema:
  username: str
  password: password
  pin: str
  vehicle_id: str
  region: list(US|Canada|Europe)
  brand: list(Hyundai|Kia)
  port: port
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web API for vehicle control
image: ghcr.io/fhfournier/home-assistant-hyundai-palisade-command/{arch}
